# Generated by Django 3.2.23 on 2024-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemesinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=50)),
                ('citizensip', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('rationcard', models.CharField(max_length=50)),
                ('employmentStatus', models.CharField(max_length=50)),
                ('aadhaarnumber', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
