# Generated by Django 3.2.23 on 2024-01-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_schemesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemesinfo',
            name='aadhaarnumber',
            field=models.CharField(max_length=12),
        ),
    ]
