# Generated by Django 3.2.23 on 2024-01-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_schemesinfo_aadhaarnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('citizensip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=20)),
                ('rationcard', models.CharField(max_length=20)),
                ('employmentStatus', models.CharField(max_length=50)),
                ('aadhaarnumber', models.CharField(max_length=50)),
                ('schemename', models.CharField(max_length=50)),
            ],
        ),
    ]
