# Generated by Django 3.2.23 on 2024-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
